### Run ProcessPayroll as SystemAdmin (sysadmin:123)
POST http://localhost:4004/odata/v4/payroll/PayrollPeriods(8e000000-0000-0000-0000-000000000002)/PayrollService.ProcessPayroll
Authorization: Basic sysadmin:123
Content-Type: application/json

{
  "otRateMultiplier": 1.5
}


### 23. Payroll Executive - Approve Payroll Batch (403)
POST http://localhost:4004/odata/v4/payroll/PayrollPeriods(10000000-0000-0000-0000-000000000001)/PayrollService.ApprovePayrollBatch
Authorization: Basic payexec:
Content-Type: application/json

{}

### 24. Finance Manager - Approve Payroll Batch (200)
POST http://localhost:4004/odata/v4/payroll/PayrollPeriods(10000000-0000-0000-0000-000000000001)/PayrollService.ApprovePayrollBatch
Authorization: Basic finmgr:
Content-Type: application/json

{}

### 25. Finance Manager - Lock Payroll (200)
POST http://localhost:4004/odata/v4/payroll/PayrollPeriods(8e000000-0000-0000-0000-000000000001)/PayrollService.LockPayroll
Authorization: Basic finmgr:
Content-Type: application/json

{}

### 26. Payroll Executive - Unlock Payroll (403)
POST http://localhost:4004/odata/v4/payroll/PayrollPeriods(10000000-0000-0000-0000-000000000001)/PayrollService.UnlockPayroll
Authorization: Basic payexec:
Content-Type: application/json

{}

### 26. Payroll Executive - Unlock Payroll (403)
POST http://localhost:4004/odata/v4/payroll/PayrollPeriods(10000000-0000-0000-0000-000000000001)/PayrollService.UnlockPayroll
Authorization: Basic sysadmin:123:
Content-Type: application/json

{}

### 27. SystemAdmin - Unlock Payroll (200)
POST http://localhost:4004/odata/v4/payroll/PayrollPeriods(8e000000-0000-0000-0000-000000000001)/PayrollService.UnlockPayroll
Authorization: Basic sysadmin:
Content-Type: application/json

{}
###
POST http://localhost:4004/odata/v4/payroll/PayrollPeriods(8e000000-0000-0000-0000-000000000002)/PayrollService.ProcessPayroll
Authorization: Basic sysadmin:
Content-Type: application/json

{ "otRateMultiplier": 1.5 }

###
GET http://localhost:4004/odata/v4/payroll/PayrollProcesses?$filter=payrollPeriod_ID eq 8e000000-0000-0000-0000-000000000002
Authorization: Basic sysadmin:

###
POST http://localhost:4004/odata/v4/payroll/PayrollProcesses(1a5aa26f-dc60-48a9-befa-50964cceb584)/PayrollService.RecalculatePayroll
Authorization: Basic payexec:
Content-Type: application/json

{}


